In [5]:
import fitz
from tqdm.auto import tqdm
import os

pdf_path = "../dataset/human-nutrition-text.pdf"

def text_formatter(text: str) -> str:
    """Performs minor formatting on text."""
    
    cleaned_text = text.replace("\n", " ").strip()
    return cleaned_text

def open_and_read_pdf(pdf_path: str) -> list[dict]:
    """
    Opens a PDF file, reads its text content page by page, and collects statistics.

    Parameters:
        pdf_path (str): The file path to the PDF document to be opened and read.

    Returns:
        list[dict]: A list of dictionaries, each containing the page number
        (adjusted), character count, word count, sentence count, token count, and the extracted text
        for each page.
    """
    doc = fitz.open(pdf_path)  # open a document
    pages_and_texts = []
    for page_number, page in tqdm(enumerate(doc)):  # iterate the document pages
        text = page.get_text()  # get plain text encoded as UTF-8
        text = text_formatter(text)
        pages_and_texts.append({"page_number": page_number - 41,  # adjust page numbers since our PDF starts on page 42
                                "page_char_count": len(text),
                                "page_word_count": len(text.split(" ")),
                                "page_sentence_count_raw": len(text.split(". ")),
                                "page_token_count": len(text) / 4,  # 1 token = ~4 chars
                                "text": text})
    return pages_and_texts

if not os.path.exists(pdf_path):
    print("[INFO] File doesn't exist")
else:
    pages_and_texts = open_and_read_pdf(pdf_path=pdf_path)

0it [00:00, ?it/s]

In [6]:
pages_and_texts[:2]

[{'page_number': -41,
  'page_char_count': 29,
  'page_word_count': 4,
  'page_sentence_count_raw': 1,
  'page_token_count': 7.25,
  'text': 'Human Nutrition: 2020 Edition'},
 {'page_number': -40,
  'page_char_count': 0,
  'page_word_count': 1,
  'page_sentence_count_raw': 1,
  'page_token_count': 0.0,
  'text': ''}]

In [7]:
pages_and_texts[1044]

{'page_number': 1003,
 'page_char_count': 1308,
 'page_word_count': 221,
 'page_sentence_count_raw': 13,
 'page_token_count': 327.0,
 'text': 'Giardia lamblia is another parasite that is found in contaminated  drinking water. In addition, it lives in the intestinal tracts of animals,  and can wash into surface water and reservoirs, similar to  Cryptosporidium. Giardia causes giardiasis, with symptoms that  include abdominal cramping and diarrhea within one to three days.  Although most people recover within one to two weeks, the disease  can lead to a chronic condition, especially in people with  compromised immune systems.  The  parasite  Toxoplasma  gondii  causes  the  infection  toxoplasmosis, which is a leading cause of death attributed to  foodborne illness in the United States. More than sixty million  Americans carry Toxoplasma gondii, but very few have symptoms.  Typically, the body’s immune system keeps the parasite from  causing disease. Sources include raw or undercooked meat and  unwashed fruits and vegetables. Handling the feces of a cat with an  acute infection can also lead to the disease.4  Mold Toxins  Mold can grow on fruits, vegetables, grains, meats, poultry, and  dairy products, and typically appears as gray or green “fur.”  4.\xa0Centers for Disease Control and Prevention. (2010).  “Parasites.” Last updated November 2, 2010.  http:/ /www.cdc.gov/parasites/food.html.  The Causes of Food Contamination  |  1003'}

In [8]:
import random

random.sample(pages_and_texts, k=3)

[{'page_number': 869,
  'page_char_count': 1003,
  'page_word_count': 170,
  'page_sentence_count_raw': 7,
  'page_token_count': 250.75,
  'text': 'often mimic their behavior and eating habits. Parents must continue  to help their school-aged children and adolescents establish healthy  eating habits and attitudes toward food. Their primary role is to  bring a wide variety of health-promoting foods into the home, so  that their children can make good choices.  \xa0 Learning Activities  Technology Note: The second edition of the Human  Nutrition Open Educational Resource (OER) textbook  features interactive learning activities.\xa0 These activities are  available in the web-based textbook and not available in the  downloadable versions (EPUB, Digital PDF, Print_PDF, or  Open Document).  Learning activities may be used across various mobile  devices, however, for the best user experience it is strongly  recommended that users complete these activities using a  desktop or laptop computer and in Google Chrome.  \xa0 An interactive or media element has been  excluded from this version of the text. You can  view it online here:  Introduction  |  869'},
 {'page_number': 188,
  'page_char_count': 1168,
  'page_word_count': 176,
  'page_sentence_count_raw': 8,
  'page_token_count': 292.0,
  'text': 'Sage  Lean meats, stews, biscuits, tomatoes, green beans, fish,  lima beans, onions, lean pork  Savory  Salads, lean pork, lean ground meats, soups, green beans,  squash, tomatoes, lima beans, peas  Thyme  Lean meats (especially veal and lean pork), sauces, soups,  onions, peas, tomatoes, salads  Turmeric  Lean meats, fish, sauces, rice  Source: Shaking the Salt Habit. American Heart Association.  http:/ /www.heart.org/HEARTORG/Conditions/ HighBloodPressure/PreventionTreatmentofHighBloodPressure/ Shaking-the-Salt-Habit_UCM_303241_Article.jsp. Updated June 6,  2012. Accessed September 22, 2017.  Learning Activities  Technology Note: The second edition of the Human  Nutrition Open Educational Resource (OER) textbook  features interactive learning activities.\xa0 These activities are  available in the web-based textbook and not available in the  downloadable versions (EPUB, Digital PDF, Print_PDF, or  Open Document).  Learning activities may be used across various mobile  devices, however, for the best user experience it is strongly  recommended that users complete these activities using a  desktop or laptop computer and in Google Chrome.  \xa0 188  |  Sodium'},
 {'page_number': 852,
  'page_char_count': 1015,
  'page_word_count': 179,
  'page_sentence_count_raw': 12,
  'page_token_count': 253.75,
  'text': 'Image by  kazuend on  unsplash.co m / CC0  Toddler Years  UNIVERSITY OF HAWAI‘I AT MĀNOA FOOD SCIENCE AND HUMAN  NUTRITION PROGRAM AND HUMAN NUTRITION PROGRAM  Major physiological changes continue into the toddler years. Unlike  in infancy, the limbs grow much faster than the trunk, which gives  the body a more proportionate appearance. By the end of the third  year, a toddler is taller and more slender than an infant, with a  more erect posture. As the child grows, bone density increases  and bone tissue gradually replaces cartilage. This process known as  ossification is not completed until puberty.1Journey across the life  span: Human development and health promotion. F.A. Davis Co.  Developmental milestones include running, drawing, toilet  training, and self-feeding. How a toddler acts, speaks, learns, and  eats offers important clues about their development. By the age of  two, children have advanced from infancy and are on their way to  1.\xa0Polan, E., & Taylor, D. (2003).  852  |  Toddler Years'}]

In [9]:
import pandas as pd

df = pd.DataFrame(pages_and_texts)
df

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,text
0,-41,29,4,1,7.25,Human Nutrition: 2020 Edition
1,-40,0,1,1,0.00,
2,-39,320,54,1,80.00,Human Nutrition: 2020 Edition UNIVERSITY OF ...
3,-38,212,32,1,53.00,Human Nutrition: 2020 Edition by University of...
4,-37,797,145,2,199.25,Contents Preface University of Hawai‘i at Mā...
...,...,...,...,...,...,...
1203,1162,1676,252,18,419.00,39. Exercise 10.2 & 11.3 reused “Egg Oval Food...
1204,1163,1617,254,10,404.25,Images / Pixabay License; “Pumpkin Cartoon Ora...
1205,1164,1715,261,13,428.75,Flashcard Images Note: Most images in the fla...
1206,1165,1733,268,13,433.25,ShareAlike 11. Organs reused “Pancreas Organ ...
1207,1166,257,44,3,64.25,23. Vitamin D reused “The Functions of Vitamin...

In [10]:
# Get stats
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count
count,1208.00,1208.00,1208.00,1208.00,1208.00
mean,562.50,1148.59,198.89,9.97,287.15
std,348.86,560.44,95.75,6.19,140.11
min,-41.00,0.00,1.00,1.00,0.00
25%,260.75,762.75,134.00,4.00,190.69
50%,562.50,1232.50,215.00,10.00,308.12
75%,864.25,1605.25,271.25,14.00,401.31
max,1166.00,2308.00,429.00,32.00,577.00

In [12]:
from spacy.lang.en import English

nlp = English()

nlp.add_pipe("sentencizer")

for item in tqdm(pages_and_texts):
    item["sentences"] = list(nlp(item["text"]).sents)
    
    # Make sure all sentences are strings
    item["sentences"] = [str(sentence) for sentence in item["sentences"]]
    
    # Count the sentences 
    item["page_sentence_count_spacy"] = len(item["sentences"])

  0%|          | 0/1208 [00:00<?, ?it/s]

In [13]:
random.sample(pages_and_texts, k=1)

[{'page_number': 183,
  'page_char_count': 165,
  'page_word_count': 37,
  'page_sentence_count_raw': 2,
  'page_token_count': 41.25,
  'text': 'Sodium  levels in  milligrams is  a required  listing on a  Nutrition  Facts label.  Sodium on the Nutrition Facts Panel  Figure 3.10 Nutrition Label  Sodium  |  183',
  'sentences': ['Sodium  levels in  milligrams is  a required  listing on a  Nutrition  Facts label.',
   ' Sodium on the Nutrition Facts Panel  Figure 3.10 Nutrition Label  Sodium  |  183'],
  'page_sentence_count_spacy': 2}]

In [14]:
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,page_sentence_count_spacy
count,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00
mean,562.50,1148.59,198.89,9.97,287.15,10.32
std,348.86,560.44,95.75,6.19,140.11,6.30
min,-41.00,0.00,1.00,1.00,0.00,0.00
25%,260.75,762.75,134.00,4.00,190.69,5.00
50%,562.50,1232.50,215.00,10.00,308.12,10.00
75%,864.25,1605.25,271.25,14.00,401.31,15.00
max,1166.00,2308.00,429.00,32.00,577.00,28.00

# Chuncking

In [15]:
# Define split size to turn groups of sentences into chunks
num_sentence_chunk_size = 10 

# Create a function that recursively splits a list into desired sizes
def split_list(input_list: list, 
               slice_size: int) -> list[list[str]]:
    """
    Splits the input_list into sublists of size slice_size (or as close as possible).

    For example, a list of 17 sentences would be split into two lists of [[10], [7]]
    """
    return [input_list[i:i + slice_size] for i in range(0, len(input_list), slice_size)]

# Loop through pages and texts and split sentences into chunks
for item in tqdm(pages_and_texts):
    item["sentence_chunks"] = split_list(input_list=item["sentences"],
                                         slice_size=num_sentence_chunk_size)
    item["num_chunks"] = len(item["sentence_chunks"])

  0%|          | 0/1208 [00:00<?, ?it/s]

In [16]:
# Sample an example from the group (note: many samples have only 1 chunk as they have <=10 sentences total)
random.sample(pages_and_texts, k=1)

[{'page_number': 503,
  'page_char_count': 1772,
  'page_word_count': 289,
  'page_sentence_count_raw': 14,
  'page_token_count': 443.0,
  'text': 'high levels of activity (about one hour of exercise per day).  Moreover, most members eat breakfast every day, watch fewer than  ten hours of television per week, and weigh themselves at least once  per week. About half of them lost weight on their own, and the  other half used some type of weight-loss program. In most scientific  studies successful weight loss is accomplished only by changing the  diet and by increasing physical activity. Doing one without the other  limits the amount of weight lost and the length of time that weight  loss is sustained. On an individual level it is quite possible to achieve  successful weight loss, as over ten thousand Americans can attest.  Moreover, losing as little as 10 percent of your body weight can  significantly improve health and reduce disease risk.4  You do not have to be overweight or obese to reap benefits from  eating a healthier diet and increasing physical activity as both  provide numerous benefits beyond weight loss and maintenance.  Evidence-Based Dietary Recommendations  The 2015 Dietary Guidelines for Americans offers specific,  evidence-based recommendations for dietary changes aimed at  keeping calorie intake in balance with physical activity, which is key  for weight management. These recommendations include:  Follow a healthy eating pattern that accounts for all foods and  beverages within an appropriate calorie level that includes:  4.\xa0Clinical Guidelines on the Identification, Evaluation, and  Treatment of Overweight and Obesity in Adults: The  Evidence Report. National Heart, Lung, and Blood  Institute. 1998, 51S–210S. http:/ /www.ncbi.nlm.nih.gov/ books/NBK2003/. Accessed September 22, 2017.  Dietary, Behavioral, and Physical Activity Recommendations for Weight Management  |  503',
  'sentences': ['high levels of activity (about one hour of exercise per day).',
   ' Moreover, most members eat breakfast every day, watch fewer than  ten hours of television per week, and weigh themselves at least once  per week.',
   'About half of them lost weight on their own, and the  other half used some type of weight-loss program.',
   'In most scientific  studies successful weight loss is accomplished only by changing the  diet and by increasing physical activity.',
   'Doing one without the other  limits the amount of weight lost and the length of time that weight  loss is sustained.',
   'On an individual level it is quite possible to achieve  successful weight loss, as over ten thousand Americans can attest.',
   ' Moreover, losing as little as 10 percent of your body weight can  significantly improve health and reduce disease risk.4  You do not have to be overweight or obese to reap benefits from  eating a healthier diet and increasing physical activity as both  provide numerous benefits beyond weight loss and maintenance.',
   ' Evidence-Based Dietary Recommendations  The 2015 Dietary Guidelines for Americans offers specific,  evidence-based recommendations for dietary changes aimed at  keeping calorie intake in balance with physical activity, which is key  for weight management.',
   'These recommendations include:  Follow a healthy eating pattern that accounts for all foods and  beverages within an appropriate calorie level that includes:  4.',
   '\xa0Clinical Guidelines on the Identification, Evaluation, and  Treatment of Overweight and Obesity in Adults: The  Evidence Report.',
   'National Heart, Lung, and Blood  Institute.',
   '1998, 51S–210S. http:/ /www.ncbi.nlm.nih.gov/ books/NBK2003/. Accessed September 22, 2017.',
   ' Dietary, Behavioral, and Physical Activity Recommendations for Weight Management  |  503'],
  'page_sentence_count_spacy': 13,
  'sentence_chunks': [['high levels of activity (about one hour of exercise per day).',
    ' Moreover, most members eat breakfast every day, watch fewer than  ten hours of television per week, and weigh themselves at least once  per week.',
    'About half of them lost weight on their own, and the  other half used some type of weight-loss program.',
    'In most scientific  studies successful weight loss is accomplished only by changing the  diet and by increasing physical activity.',
    'Doing one without the other  limits the amount of weight lost and the length of time that weight  loss is sustained.',
    'On an individual level it is quite possible to achieve  successful weight loss, as over ten thousand Americans can attest.',
    ' Moreover, losing as little as 10 percent of your body weight can  significantly improve health and reduce disease risk.4  You do not have to be overweight or obese to reap benefits from  eating a healthier diet and increasing physical activity as both  provide numerous benefits beyond weight loss and maintenance.',
    ' Evidence-Based Dietary Recommendations  The 2015 Dietary Guidelines for Americans offers specific,  evidence-based recommendations for dietary changes aimed at  keeping calorie intake in balance with physical activity, which is key  for weight management.',
    'These recommendations include:  Follow a healthy eating pattern that accounts for all foods and  beverages within an appropriate calorie level that includes:  4.',
    '\xa0Clinical Guidelines on the Identification, Evaluation, and  Treatment of Overweight and Obesity in Adults: The  Evidence Report.'],
   ['National Heart, Lung, and Blood  Institute.',
    '1998, 51S–210S. http:/ /www.ncbi.nlm.nih.gov/ books/NBK2003/. Accessed September 22, 2017.',
    ' Dietary, Behavioral, and Physical Activity Recommendations for Weight Management  |  503']],
  'num_chunks': 2}]

In [17]:
# Create a DataFrame to get stats
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,page_sentence_count_spacy,num_chunks
count,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00
mean,562.50,1148.59,198.89,9.97,287.15,10.32,1.53
std,348.86,560.44,95.75,6.19,140.11,6.30,0.64
min,-41.00,0.00,1.00,1.00,0.00,0.00,0.00
25%,260.75,762.75,134.00,4.00,190.69,5.00,1.00
50%,562.50,1232.50,215.00,10.00,308.12,10.00,1.00
75%,864.25,1605.25,271.25,14.00,401.31,15.00,2.00
max,1166.00,2308.00,429.00,32.00,577.00,28.00,3.00

# Splitting Chunks

In [18]:
import re

# Split each chunk into its own item
pages_and_chunks = []
for item in tqdm(pages_and_texts):
    for sentence_chunk in item["sentence_chunks"]:
        chunk_dict = {}
        chunk_dict["page_number"] = item["page_number"]
        
        # Join the sentences together into a paragraph-like structure, aka a chunk (so they are a single string)
        joined_sentence_chunk = "".join(sentence_chunk).replace("  ", " ").strip()
        joined_sentence_chunk = re.sub(r'\.([A-Z])', r'. \1', joined_sentence_chunk) # ".A" -> ". A" for any full-stop/capital letter combo 
        chunk_dict["sentence_chunk"] = joined_sentence_chunk

        # Get stats about the chunk
        chunk_dict["chunk_char_count"] = len(joined_sentence_chunk)
        chunk_dict["chunk_word_count"] = len([word for word in joined_sentence_chunk.split(" ")])
        chunk_dict["chunk_token_count"] = len(joined_sentence_chunk) / 4 # 1 token = ~4 characters
        
        pages_and_chunks.append(chunk_dict)

# How many chunks do we have?
len(pages_and_chunks)

  0%|          | 0/1208 [00:00<?, ?it/s]

1843

In [19]:
# View a random sample
random.sample(pages_and_chunks, k=1)

[{'page_number': 1019,
  'sentence_chunk': 'Food Preservation UNIVERSITY OF HAWAI‘I AT MĀNOA FOOD SCIENCE AND HUMAN NUTRITION PROGRAM AND HUMAN NUTRITION PROGRAM Food preservation protects consumers from harmful or toxic food. There are different ways to preserve food. Some are ancient methods that have been practiced for generations, such as curing, smoking, pickling, salting, fermenting, canning, and preserving fruit in the form of jam. Others include the use of modern techniques and technology, including drying, vacuum packing, pasteurization, and freezing and refrigeration. Preservation guards against foodborne illnesses, and also protects the flavor, color, moisture content, or nutritive value of food. Food Irradiation: What You Need to Know Irradiation does not make foods radioactive, compromise nutritional quality, or noticeably change the taste, texture, or appearance of food. In fact, any changes made by irradiation are so minimal that it is not easy to tell if a food has been irradiated. Food irradiation (the application of ionizing radiation to food) is a technology that improves the safety and extends the shelf life of foods by reducing or eliminating microorganisms and insects. Like pasteurizing milk and canning fruits and vegetables, irradiation can make food safer for the consumer. The Food and Drug Administration (FDA) is responsible for regulating the sources of radiation that are used to irradiate food.',
  'chunk_char_count': 1400,
  'chunk_word_count': 210,
  'chunk_token_count': 350.0}]

In [20]:
df = pd.DataFrame(pages_and_chunks)
df.describe().round(2)

       page_number  chunk_char_count  chunk_word_count  chunk_token_count
count      1843.00           1843.00           1843.00            1843.00
mean        583.38            734.83            112.72             183.71
std         347.79            447.43             71.07             111.86
min         -41.00             12.00              3.00               3.00
25%         280.50            315.00             45.00              78.75
50%         586.00            746.00            114.00             186.50
75%         890.00           1118.50            173.00             279.62
max        1166.00           1831.00            297.00             457.75

In [21]:
# Show random chunks with under 30 tokens in length
min_token_length = 30
for row in df[df["chunk_token_count"] <= min_token_length].sample(5).iterrows():
    print(f'Chunk token count: {row[1]["chunk_token_count"]} | Text: {row[1]["sentence_chunk"]}')

Chunk token count: 10.5 | Text: 442 | Health Consequences of Alcohol Abuse
Chunk token count: 16.0 | Text: Accessed January 20, 2018. The Effect of New Technologies | 1031
Chunk token count: 8.0 | Text: For example, 856 | Toddler Years
Chunk token count: 18.75 | Text: Published February 6, 2018. Accessed April 15, 2018. Comparing Diets | 1055
Chunk token count: 17.5 | Text: The Obesity Myth. Gotham Books. Calories In Versus Calories Out | 1069

In [22]:
pages_and_chunks_over_min_token_len = df[df["chunk_token_count"] > min_token_length].to_dict(orient="records")
pages_and_chunks_over_min_token_len[:2]

[{'page_number': -39,
  'sentence_chunk': 'Human Nutrition: 2020 Edition UNIVERSITY OF HAWAI‘I AT MĀNOA FOOD SCIENCE AND HUMAN NUTRITION PROGRAM ALAN TITCHENAL, SKYLAR HARA, NOEMI ARCEO CAACBAY, WILLIAM MEINKE-LAU, YA-YUN YANG, MARIE KAINOA FIALKOWSKI REVILLA, JENNIFER DRAPER, GEMADY LANGFELDER, CHERYL GIBBY, CHYNA NICOLE CHUN, AND ALLISON CALABRESE',
  'chunk_char_count': 308,
  'chunk_word_count': 42,
  'chunk_token_count': 77.0},
 {'page_number': -38,
  'sentence_chunk': 'Human Nutrition: 2020 Edition by University of Hawai‘i at Mānoa Food Science and Human Nutrition Program is licensed under a Creative Commons Attribution 4.0 International License, except where otherwise noted.',
  'chunk_char_count': 210,
  'chunk_word_count': 30,
  'chunk_token_count': 52.5}]

# Embedding chunks

In [24]:
from sentence_transformers import SentenceTransformer
embedding_model = SentenceTransformer(model_name_or_path="all-mpnet-base-v2", 
                                      device="cpu")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [25]:
%%time

embedding_model.to("cuda")

for item in tqdm(pages_and_chunks_over_min_token_len):
    item["embedding"] = embedding_model.encode(item["sentence_chunk"])

  0%|          | 0/1680 [00:00<?, ?it/s]

CPU times: user 8min 42s, sys: 23.4 s, total: 9min 5s
Wall time: 26 s

In [26]:
# Turn text chunks into a single list
text_chunks = [item["sentence_chunk"] for item in pages_and_chunks_over_min_token_len]

In [27]:
%%time

# Embed all texts in batches
text_chunk_embeddings = embedding_model.encode(text_chunks,
                                               batch_size=32,
                                               convert_to_tensor=True)

text_chunk_embeddings

CPU times: user 3min, sys: 9.89 s, total: 3min 10s
Wall time: 7.51 s

tensor([[ 0.0674,  0.0902, -0.0051,  ..., -0.0221, -0.0232,  0.0126],
        [ 0.0552,  0.0592, -0.0166,  ..., -0.0120, -0.0103,  0.0227],
        [ 0.0280,  0.0340, -0.0206,  ..., -0.0054,  0.0213,  0.0313],
        ...,
        [ 0.0771,  0.0098, -0.0122,  ..., -0.0409, -0.0752, -0.0241],
        [ 0.1030, -0.0165,  0.0083,  ..., -0.0574, -0.0283, -0.0295],
        [ 0.0864, -0.0125, -0.0113,  ..., -0.0522, -0.0337, -0.0299]],
       device='cuda:0')

In [28]:
# Save embeddings to file
text_chunks_and_embeddings_df = pd.DataFrame(pages_and_chunks_over_min_token_len)
embeddings_df_save_path = "text_chunks_and_embeddings_df.csv"
text_chunks_and_embeddings_df.to_csv(embeddings_df_save_path, index=False)

In [29]:
# Import saved file and view
text_chunks_and_embedding_df_load = pd.read_csv(embeddings_df_save_path)
text_chunks_and_embedding_df_load.head()

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding
0,-39,Human Nutrition: 2020 Edition UNIVERSITY OF HA...,308,42,77.00,[ 6.74242675e-02 9.02281329e-02 -5.09549584e-...
1,-38,Human Nutrition: 2020 Edition by University of...,210,30,52.50,[ 5.52156232e-02 5.92139289e-02 -1.66167393e-...
2,-37,Contents Preface University of Hawai‘i at Māno...,766,114,191.50,[ 2.79801879e-02 3.39813940e-02 -2.06426606e-...
3,-36,Lifestyles and Nutrition University of Hawai‘i...,941,142,235.25,[ 6.82566836e-02 3.81274782e-02 -8.46855063e-...
4,-35,The Cardiovascular System University of Hawai‘...,998,152,249.50,[ 3.30264308e-02 -8.49763770e-03 9.57159698e-...

In [30]:
import random

import torch
import numpy as np 
import pandas as pd

device = "cuda" if torch.cuda.is_available() else "cpu"

# Import texts and embedding df
text_chunks_and_embedding_df = pd.read_csv("text_chunks_and_embeddings_df.csv")

# Convert embedding column back to np.array (it got converted to string when it got saved to CSV)
text_chunks_and_embedding_df["embedding"] = text_chunks_and_embedding_df["embedding"].apply(lambda x: np.fromstring(x.strip("[]"), sep=" "))

# Convert texts and embedding df to list of dicts
pages_and_chunks = text_chunks_and_embedding_df.to_dict(orient="records")

# Convert embeddings to torch tensor and send to device (note: NumPy arrays are float64, torch tensors are float32 by default)
embeddings = torch.tensor(np.array(text_chunks_and_embedding_df["embedding"].tolist()), dtype=torch.float32).to(device)
embeddings.shape

torch.Size([1680, 768])

In [31]:
text_chunks_and_embedding_df.head()

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding
0,-39,Human Nutrition: 2020 Edition UNIVERSITY OF HA...,308,42,77.00,"[0.0674242675, 0.0902281329, -0.00509549584, -..."
1,-38,Human Nutrition: 2020 Edition by University of...,210,30,52.50,"[0.0552156232, 0.0592139289, -0.0166167393, -0..."
2,-37,Contents Preface University of Hawai‘i at Māno...,766,114,191.50,"[0.0279801879, 0.033981394, -0.0206426606, 0.0..."
3,-36,Lifestyles and Nutrition University of Hawai‘i...,941,142,235.25,"[0.0682566836, 0.0381274782, -0.00846855063, -..."
4,-35,The Cardiovascular System University of Hawai‘...,998,152,249.50,"[0.0330264308, -0.0084976377, 0.00957159698, -..."

In [32]:
from sentence_transformers import util
# 1. Define the query
# Note: This could be anything. But since we're working with a nutrition textbook, we'll stick with nutrition-based queries.
query = "macronutrients functions"
print(f"Query: {query}")

# 2. Embed the query to the same numerical space as the text examples 
# Note: It's important to embed your query with the same model you embedded your examples with.
query_embedding = embedding_model.encode(query, convert_to_tensor=True)

# 3. Get similarity scores with the dot product (we'll time this for fun)
from time import perf_counter as timer

start_time = timer()
dot_scores = util.dot_score(a=query_embedding, b=embeddings)[0]
end_time = timer()

print(f"Time take to get scores on {len(embeddings)} embeddings: {end_time-start_time:.5f} seconds.")

# 4. Get the top-k results (we'll keep this to 5)
top_results_dot_product = torch.topk(dot_scores, k=5)
top_results_dot_product

Query: macronutrients functions
Time take to get scores on 1680 embeddings: 0.00048 seconds.

torch.return_types.topk(
values=tensor([0.6926, 0.6738, 0.6646, 0.6536, 0.6473], device='cuda:0'),
indices=tensor([42, 47, 41, 51, 46], device='cuda:0'))

In [34]:
# Define helper function to print wrapped text 
import textwrap

def print_wrapped(text, wrap_length=80):
    wrapped_text = textwrap.fill(text, wrap_length)
    print(wrapped_text)

In [35]:
print(f"Query: '{query}'\n")
print("Results:")
# Loop through zipped together scores and indicies from torch.topk
for score, idx in zip(top_results_dot_product[0], top_results_dot_product[1]):
    print(f"Score: {score:.4f}")
    # Print relevant sentence chunk (since the scores are in descending order, the most relevant chunk will be first)
    print("Text:")
    print_wrapped(pages_and_chunks[idx]["sentence_chunk"])
    # Print the page number too so we can reference the textbook further (and check the results)
    print(f"Page number: {pages_and_chunks[idx]['page_number']}")
    print("\n")

Query: 'macronutrients functions'

Results:
Score: 0.6926
Text:
Macronutrients Nutrients that are needed in large amounts are called
macronutrients. There are three classes of macronutrients: carbohydrates,
lipids, and proteins. These can be metabolically processed into cellular energy.
The energy from macronutrients comes from their chemical bonds. This chemical
energy is converted into cellular energy that is then utilized to perform work,
allowing our bodies to conduct their basic functions. A unit of measurement of
food energy is the calorie. On nutrition food labels the amount given for
“calories” is actually equivalent to each calorie multiplied by one thousand. A
kilocalorie (one thousand calories, denoted with a small “c”) is synonymous with
the “Calorie” (with a capital “C”) on nutrition food labels. Water is also a
macronutrient in the sense that you require a large amount of it, but unlike the
other macronutrients, it does not yield calories. Carbohydrates Carbohydrates
are molecules composed of carbon, hydrogen, and oxygen.
Page number: 5


Score: 0.6738
Text:
Water There is one other nutrient that we must have in large quantities: water.
Water does not contain carbon, but is composed of two hydrogens and one oxygen
per molecule of water. More than 60 percent of your total body weight is water.
Without it, nothing could be transported in or out of the body, chemical
reactions would not occur, organs would not be cushioned, and body temperature
would fluctuate widely. On average, an adult consumes just over two liters of
water per day from food and drink combined. Since water is so critical for
life’s basic processes, the amount of water input and output is supremely
important, a topic we will explore in detail in Chapter 4. Micronutrients
Micronutrients are nutrients required by the body in lesser amounts, but are
still essential for carrying out bodily functions. Micronutrients include all
the essential minerals and vitamins. There are sixteen essential minerals and
thirteen vitamins (See Table 1.1 “Minerals and Their Major Functions” and Table
1.2 “Vitamins and Their Major Functions” for a complete list and their major
functions). In contrast to carbohydrates, lipids, and proteins, micronutrients
are not sources of energy (calories), but they assist in the process as
cofactors or components of enzymes (i.e., coenzymes).
Page number: 8


Score: 0.6646
Text:
Learning Objectives By the end of this chapter, you will be able to: • Describe
basic concepts in nutrition • Describe factors that affect your nutritional
needs • Describe the importance of research and scientific methods to
understanding nutrition What are Nutrients? The foods we eat contain nutrients.
Nutrients are substances required by the body to perform its basic functions.
Nutrients must be obtained from our diet, since the human body does not
synthesize or produce them. Nutrients have one or more of three basic functions:
they provide energy, contribute to body structure, and/or regulate chemical
processes in the body. These basic functions allow us to detect and respond to
environmental surroundings, move, excrete wastes, respire (breathe), grow, and
reproduce. There are six classes of nutrients required for the body to function
and maintain overall health. These are carbohydrates, lipids, proteins, water,
vitamins, and minerals. Foods also contain non-nutrients that may be harmful
(such as natural toxins common in plant foods and additives like some dyes and
preservatives) or beneficial (such as antioxidants). 4 | Introduction
Page number: 4


Score: 0.6536
Text:
Vitamins Major Functions Water-soluble Thiamin (B1) Coenzyme, energy metabolism
assistance Riboflavin (B2 ) Coenzyme, energy metabolism assistance Niacin (B3)
Coenzyme, energy metabolism assistance Pantothenic acid (B5) Coenzyme, energy
metabolism assistance Pyridoxine (B6) Coenzyme, amino acid synthesis assistance
Biotin (B7) Coenzyme, amino acid and fatty acid metabolism Folate (B9) Coenzyme,
essential for growth Cobalamin (B12) Coenzyme, red blood cell synthesis C
(ascorbic acid) Collagen synthesis, antioxidant Fat-soluble A Vision,
reproduction, immune system function D Bone and teeth health maintenance, immune
system function E Antioxidant, cell membrane protection K Bone and teeth health
maintenance, blood clotting Vitamin deficiencies can cause severe health
problems and even death. For example, a deficiency in niacin causes a disease
called pellagra, which was common in the early twentieth century in some parts
of America. The common signs and symptoms of pellagra are known as the
“4D’s—diarrhea, dermatitis, dementia, and death.” Until scientists found out
that better diets relieved the signs and symptoms of pellagra, many people with
the disease ended up hospitalized in insane asylums awaiting death. Other
vitamins were also found to prevent certain disorders and diseases such as
scurvy (vitamin C), night blindness vitamin A, and rickets (vitamin D). Table
1.3 Functions of Nutrients Introduction | 11
Page number: 11


Score: 0.6473
Text:
Figure 1.1 The Macronutrie nts: Carbohydrat es, Lipids, Protein, and Water
Proteins Proteins are macromolecules composed of chains of subunits called amino
acids. Amino acids are simple subunits composed of carbon, oxygen, hydrogen, and
nitrogen. Food sources of proteins include meats, dairy products, seafood, and a
variety of different plant- based foods, most notably soy. The word protein
comes from a Greek word meaning “of primary importance,” which is an apt
description of these macronutrients; they are also known colloquially as the
“workhorses” of life. Proteins provide four kilocalories of energy per gram;
however providing energy is not protein’s most important function. Proteins
provide structure to bones, muscles and skin, and play a role in conducting most
of the chemical reactions that take place in the body. Scientists estimate that
greater than one-hundred thousand different proteins exist within the human
body. The genetic codes in DNA are basically protein recipes that determine the
order in which 20 different amino acids are bound together to make thousands of
specific proteins. Figure 1.1 The Macronutrients: Carbohydrates, Lipids,
Protein, and Water Introduction | 7
Page number: 7

In [36]:
# Get GPU available memory
import torch
gpu_memory_bytes = torch.cuda.get_device_properties(0).total_memory
gpu_memory_gb = round(gpu_memory_bytes / (2**30))
print(f"Available GPU memory: {gpu_memory_gb} GB")

Available GPU memory: 32 GB

In [37]:
torch.cuda.get_device_capability(0)[0]

7

In [38]:
# Note: the following is Gemma focused, however, there are more and more LLMs of the 2B and 7B size appearing for local use.
if gpu_memory_gb < 5.1:
    print(f"Your available GPU memory is {gpu_memory_gb}GB, you may not have enough memory to run a Gemma LLM locally without quantization.")
elif gpu_memory_gb < 8.1:
    print(f"GPU memory: {gpu_memory_gb} | Recommended model: Gemma 2B in 4-bit precision.")
    use_quantization_config = True 
    model_id = "google/gemma-2b-it"
elif gpu_memory_gb < 19.0:
    print(f"GPU memory: {gpu_memory_gb} | Recommended model: Gemma 2B in float16 or Gemma 7B in 4-bit precision.")
    use_quantization_config = False 
    model_id = "google/gemma-2b-it"
elif gpu_memory_gb > 19.0:
    print(f"GPU memory: {gpu_memory_gb} | Recommend model: Gemma 7B in 4-bit or float16 precision.")
    use_quantization_config = False 
    model_id = "google/gemma-7b-it"

print(f"use_quantization_config set to: {use_quantization_config}")
print(f"model_id set to: {model_id}")

GPU memory: 32 | Recommend model: Gemma 7B in 4-bit or float16 precision.
use_quantization_config set to: False
model_id set to: google/gemma-7b-it

In [47]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers.utils import is_flash_attn_2_available 

# 1. Create quantization config for smaller model loading (optional)
# Requires !pip install bitsandbytes accelerate, see: https://github.com/TimDettmers/bitsandbytes, https://huggingface.co/docs/accelerate/
# For models that require 4-bit quantization (use this if you have low GPU memory available)
from transformers import BitsAndBytesConfig
quantization_config = BitsAndBytesConfig(load_in_4bit=True,
                                         bnb_4bit_compute_dtype=torch.float16)

# Bonus: Setup Flash Attention 2 for faster inference, default to "sdpa" or "scaled dot product attention" if it's not available
# Flash Attention 2 requires NVIDIA GPU compute capability of 8.0 or above, see: https://developer.nvidia.com/cuda-gpus
# Requires !pip install flash-attn, see: https://github.com/Dao-AILab/flash-attention 
if (is_flash_attn_2_available()) and (torch.cuda.get_device_capability(0)[0] >= 8):
  attn_implementation = "flash_attention_2"
else:
  attn_implementation = "sdpa"
print(f"[INFO] Using attention implementation: {attn_implementation}")

# 2. Pick a model we'd like to use (this will depend on how much GPU memory you have available)
#model_id = "google/gemma-7b-it"
model_id = model_id # (we already set this above)
print(f"[INFO] Using model_id: {model_id}")

# 3. Instantiate tokenizer (tokenizer turns text into numbers ready for the model) 
tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path=model_id)

# 4. Instantiate the model
llm_model = AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path=model_id, 
                                                 torch_dtype=torch.float16, # datatype to use, we want float16
                                                 quantization_config=quantization_config if use_quantization_config else None,
                                                 low_cpu_mem_usage=False, # use full memory 
                                                 attn_implementation=attn_implementation) # which attention version to use

if not use_quantization_config: # quantization takes care of device setting automatically, so if it's not used, send model to GPU 
    llm_model.to("cuda")

[INFO] Using attention implementation: sdpa
[INFO] Using model_id: google/gemma-7b-it

tokenizer_config.json:   0%|          | 0.00/34.2k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/20.9k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/4 [00:00<?, ?it/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/2.11G [00:00<?, ?B/s]

Gemma's activation function should be approximate GeLU and not exact GeLU.
Changing the activation function to `gelu_pytorch_tanh`.if you want to use the legacy `gelu`, edit the `model.config` to set `hidden_activation=gelu`   instead of `hidden_act`. See https://github.com/huggingface/transformers/pull/29402 for more details.

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

In [48]:
llm_model

GemmaForCausalLM(
  (model): GemmaModel(
    (embed_tokens): Embedding(256000, 3072, padding_idx=0)
    (layers): ModuleList(
      (0-27): 28 x GemmaDecoderLayer(
        (self_attn): GemmaSdpaAttention(
          (q_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (k_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (v_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=3072, bias=False)
          (rotary_emb): GemmaRotaryEmbedding()
        )
        (mlp): GemmaMLP(
          (gate_proj): Linear(in_features=3072, out_features=24576, bias=False)
          (up_proj): Linear(in_features=3072, out_features=24576, bias=False)
          (down_proj): Linear(in_features=24576, out_features=3072, bias=False)
          (act_fn): PytorchGELUTanh()
        )
        (input_layernorm): GemmaRMSNorm()
        (post_attention_layernorm): GemmaRMSNorm()
      )
    )
    (norm): GemmaRMSNorm()
  )
  (lm_head): Linear(in_features=3072, out_features=256000, bias=False)
)

In [49]:
def get_model_num_params(model: torch.nn.Module):
    return sum([param.numel() for param in model.parameters()])

get_model_num_params(llm_model)

8537680896

In [50]:
def get_model_mem_size(model: torch.nn.Module):
    """
    Get how much memory a PyTorch model takes up.

    See: https://discuss.pytorch.org/t/gpu-memory-that-model-uses/56822
    """
    # Get model parameters and buffer sizes
    mem_params = sum([param.nelement() * param.element_size() for param in model.parameters()])
    mem_buffers = sum([buf.nelement() * buf.element_size() for buf in model.buffers()])

    # Calculate various model sizes
    model_mem_bytes = mem_params + mem_buffers # in bytes
    model_mem_mb = model_mem_bytes / (1024**2) # in megabytes
    model_mem_gb = model_mem_bytes / (1024**3) # in gigabytes

    return {"model_mem_bytes": model_mem_bytes,
            "model_mem_mb": round(model_mem_mb, 2),
            "model_mem_gb": round(model_mem_gb, 2)}

get_model_mem_size(llm_model)

{'model_mem_bytes': 17075361792,
 'model_mem_mb': 16284.33,
 'model_mem_gb': 15.9}

In [54]:
input_text = "Explain about macronutrients?"
print(f"Input text:\n{input_text}")

# Create prompt template for instruction-tuned model
dialogue_template = [
    {"role": "user",
     "content": input_text}
]

# Apply the chat template
prompt = tokenizer.apply_chat_template(conversation=dialogue_template,
                                       tokenize=False, # keep as raw text (not tokenized)
                                       add_generation_prompt=True)
print(f"\nPrompt (formatted):\n{prompt}")

Input text:
Explain about macronutrients?

Prompt (formatted):
<bos><start_of_turn>user
Explain about macronutrients?<end_of_turn>
<start_of_turn>model

In [55]:
%%time

# Tokenize the input text (turn it into numbers) and send it to GPU
input_ids = tokenizer(prompt, return_tensors="pt").to("cuda")
print(f"Model input (tokenized):\n{input_ids}\n")

# Generate outputs passed on the tokenized input
# See generate docs: https://huggingface.co/docs/transformers/v4.38.2/en/main_classes/text_generation#transformers.GenerationConfig 
outputs = llm_model.generate(**input_ids,
                             max_new_tokens=256) # define the maximum number of new tokens to create
print(f"Model output (tokens):\n{outputs[0]}\n")

Model input (tokenized):
{'input_ids': tensor([[     2,      2,    106,   1645,    108,  74198,   1105, 186809, 184592,
         235336,    107,    108,    106,   2516,    108]], device='cuda:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], device='cuda:0')}

Model output (tokens):
tensor([     2,      2,    106,   1645,    108,  74198,   1105, 186809, 184592,
        235336,    107,    108,    106,   2516,    108,  21404, 235269,   1517,
           603,    671,  15844,    576, 186809, 184592, 235292,    109,  12298,
          1695, 184592,    708,    573,   2149, 186809, 184592,    674,    573,
          2971,   7177,    577,   3658,   4134,    578,   2500,    578,  12158,
         29703, 235265,   2365,    708,  72780, 235269,  20361, 235269,    578,
         61926, 235265,   9573, 186809,   7208,    579,    919,    476,   2167,
          9408,   5449,    578,   6572,    476,   2167,   3619,    576,   4134,
           842,  14063, 235265,    109,    688, 156615,  56227,  66058,    109,
        235287, 110165,  56227,    708,    573,   2971, 235303, 235256,   1872,
          4303,    576,   4134, 235265,   2365,    708,  10127,   1706,   1280,
         30859, 235269,    948,    603,   1492,   1671,    604,   4134, 235265,
           108, 235287, 110165,  56227,    708,   1942,    575,  16512,   1582,
           685,  11843, 235269,  22512, 235269,  12463, 235269,  25741, 235269,
         16803, 235269,    578,  19574, 235265,    108, 235287, 110165,  56227,
          3658, 235248, 235310,  82848,    842,  14063, 235265,    109,    688,
        216954,  66058,    109, 235287,  96084,    708,   1671,    577,   2500,
           578,  12158,  29703, 235269,   7872,  44760,    578,  53186, 235269,
           578,   6676,  37132,   6900,    573,   2971, 235265,    108, 235287,
         96084,    708,   1942,    575,  16512,   1582,    685,  11827, 235269,
          5001, 235269,  12776, 235269,  31062,   3773, 235269,  22604, 235269,
        150178, 235269,    578,  22606, 235265,    108, 235287,  96084,   3658,
        235248, 235310,  82848,    842,  14063, 235265,    109,    688, 235311,
          1989,  66058,    109, 235287, 178190,    708,   1671,    577,   4659,
          4134,    578,   2029,   7459,    573,  29998, 235265,    108, 235287,
        178190,    708,   1942,    575,  16512,   1582,    685,  10605, 235269,
         13624, 235269,  11827, 235269,   5001, 235269,  22606, 235269,    578,
         15741, 235265,    108, 235287, 178190,   3658, 235248, 235315,  82848,
           842,  14063, 235265,    109,    651,   3619,    576,   1853, 186809,
          7208,    579,    674,    692,   1476,    577,  35981,   1853,   1744,
         12014], device='cuda:0')

CPU times: user 7.8 s, sys: 303 ms, total: 8.11 s
Wall time: 8.12 s

In [56]:
# Decode the output tokens to text
outputs_decoded = tokenizer.decode(outputs[0])
print(f"Model output (decoded):\n{outputs_decoded}\n")

Model output (decoded):
<bos><bos><start_of_turn>user
Explain about macronutrients?<end_of_turn>
<start_of_turn>model
Sure, here is an explanation of macronutrients:

Macronutrients are the three macronutrients that the body uses to provide energy and build and repair tissues. They are carbohydrates, proteins, and fats. Each macronutrient has a different chemical structure and provides a different amount of energy per gram.

**Carbohydrates:**

* Carbohydrates are the body's main source of energy. They are broken down into glucose, which is then used for energy.
* Carbohydrates are found in foods such as bread, pasta, rice, potatoes, fruits, and vegetables.
* Carbohydrates provide 4 kcal per gram.

**Proteins:**

* Proteins are used to build and repair tissues, produce enzymes and hormones, and transport nutrients throughout the body.
* Proteins are found in foods such as meat, fish, eggs, dairy products, beans, lentils, and nuts.
* Proteins provide 4 kcal per gram.

**Fats:**

* Fats are used to store energy and insulate the organs.
* Fats are found in foods such as butter, cheese, meat, fish, nuts, and seeds.
* Fats provide 9 kcal per gram.

The amount of each macronutrient that you need to consume each day depends